export const adminCopy = {
  title: "Administración",
  onlyAdmin: "Esta sección es solo para el administrador.",
  sections: { trabajadores: "Trabajadores", puestos: "Puestos", tarifas: "Tarifas" },
  save: "Guardar",
  saving: "Guardando…",
  cancel: "Cancelar",
  edit: "Editar",
  unavailable: "No se pudo guardar. Revisa la señal y vuelve a intentarlo.",
  required: "Este dato es obligatorio.",

  employees: {
    new: "Agregar trabajador",
    newTitle: "Nuevo trabajador",
    editTitle: "Editar trabajador",
    firstName: "Nombre",
    lastName: "Apellido",
    nationalId: "RUT",
    nationalIdHint: "Sin puntos y con guión, por ejemplo 12345678-5.",
    invalidNationalId: "Escribe el RUT sin puntos y con guión, por ejemplo 12345678-5.",
    duplicateNationalId: "Ya hay un trabajador con ese RUT.",
    active: "Activo",
    inactive: "Inactivo",
    deactivate: "Desactivar",
    deactivateTitle: "¿Desactivar a esta persona?",
    deactivateBody: (name: string) =>
      `${name} deja de aparecer en los días siguientes. Sus días ya registrados y sus pagos se conservan.`,
    deactivateConfirm: "Sí, desactivar",
    deactivating: "Desactivando…",
    reactivate: "Reactivar",
  },

  positions: {
    new: "Agregar puesto",
    newTitle: "Nuevo puesto",
    editTitle: "Editar puesto",
    code: "Código",
    codeHint: "En mayúsculas y sin tildes, por ejemplo CARDA_NUEVA.",
    invalidCode: "Usa solo mayúsculas, números y guion bajo.",
    duplicateCode: "Ya hay un puesto con ese código.",
    name: "Nombre en pantalla",
    type: "Tipo",
    types: { WORK: "Trabajo", ABSENCE: "Ausencia" },
    bonusEligible: "Cobra bono de la línea de cardas",
    triggersEqualShare: "Cambia el día a reparto igualitario",
    triggerNeedsBonus:
      "Un puesto que cambia el día a reparto igualitario también tiene que cobrar bono. Marca ambas opciones o ninguna de las dos.",
    displayOrder: "Orden en la lista",
    displayOrderHint: "Los números más bajos aparecen primero. Mantén separados Packing y Packing ACM.",
    active: "Disponible para asignar",
    yes: "Sí",
    no: "No",
  },

  rates: {
    intro:
      "Cambiar una tarifa crea una vigencia nueva desde la fecha que elijas. La vigencia actual no se edita: los días anteriores se siguen pagando con ella, y lo ya cerrado no cambia.",
    new: "Nueva vigencia",
    newTitle: "Nueva vigencia de tarifas",
    effectiveFrom: "Vigente desde",
    effectiveFromHint: "La vigencia actual termina el día anterior.",
    dailyCap: "Tope diario",
    maxAmountPerPerson: "Máximo por persona en reparto igualitario",
    rateFor: (name: string) => `Tarifa ${name}`,
    noRateForTrigger: (names: string) => `${names} no lleva tarifa: su presencia cambia el día a reparto igualitario.`,
    invalidAmount: "Escribe un monto en pesos, sin puntos.",
    mustStartLater: "La nueva vigencia tiene que empezar después de la actual.",
    current: "Vigente",
    range: (from: string, to: string | null) => (to ? `Del ${from} al ${to}` : `Desde el ${from}`),
    positionColumn: "Puesto",
    amountColumn: "Tarifa",
  },
} as const;
