export const dayCopy = {
  today: "Hoy",
  yesterday: "Ayer",
  previousDay: "Día anterior",
  nextDay: "Día siguiente",
  goToDate: "Ir a fecha",
  edit: "Editar",
  readModeNotice: "Modo lectura. Aprieta «Editar» para hacer cambios.",
  employeeColumn: "Trabajador",
  positionColumn: "Puesto",
  noEmployees: "No hay trabajadores para mostrar en esta fecha.",
  inactive: "Inactivo",
  close: "Cerrar",
  nationalId: "RUT",
  assignmentsOfMonth: (month: string) => `Puestos en ${month}`,
  noAssignmentsInMonth: "Sin puestos registrados este mes.",

  finishEditing: "Terminar edición",
  editModeNotice: "Modo edición. Cada cambio se guarda al elegir el puesto.",
  noPosition: "— Sin puesto —",
  positionGroups: {
    LINE: "Línea de cardas",
    OTHER: "Otros puestos",
    ABSENCE: "Ausencias",
  },
  positionFor: (name: string) => `Puesto de ${name}`,
  writeStatus: {
    IDLE: "",
    SAVING: "Guardando…",
    SAVED: "Guardado",
    SETTLED: "Este día ya se pagó. Solo un administrador puede cambiarlo.",
    ONE_POSITION_PER_DAY: "Esta persona ya tiene un puesto este día. Cada persona tiene un solo puesto por día.",
    UNAVAILABLE: "No se pudo guardar. Revisa la señal y vuelve a intentarlo.",
  },
  modified: "Modificado",
  historyLink: "Historial",
  historyColumn: "Historial",
  history: "Cambios",
  noHistory: "Sin cambios registrados.",
  emptyCell: "(vacío)",
  unknownUser: "alguien",
  note: "Nota",
  noNote: "Sin nota.",
  saveNote: "Guardar nota",
  noteNeedsPosition: "Elige un puesto antes de agregar una nota.",
} as const;
